<?php
declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;

/**
 * Class BaseModel
 * @package App\Models
 */
abstract class BaseModel extends Model
{
    use SoftDeletes;

    /**
     * @return void
     * @noinspection PhpUndefinedFieldInspection
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Model $model): void {
            $identifier = Auth::user()->getAuthIdentifier();
            $model->uuid = $model->uuid ?? Uuid::uuid4()->toString();
            $model->created_by = $identifier;
            $model->updated_by = $identifier;
        });

        static::updating(function (Model $model): void {
            $model->updated_by = 1;
        });
    }

    /**
     * @return HasOne
     */
    public function updatedBy(): HasOne
    {
        return $this->hasOne(User::class, 'id', 'updated_by');
    }

    /**
     * @return HasOne
     */
    public function createdBy(): HasOne
    {
        return $this->hasOne(User::class, 'id', 'created_by');
    }
}
