version: "3"

services:
  database:
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    image: mysql:5.7
    volumes:
      - ./database/config/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./database/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - ./../.env
  webserver:
    container_name: ${WEBSERVER_CONTAINER_NAME}
    restart: always
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./../src/lib/:/var/www/html/
    links:
      - database
    depends_on:
      - database
    env_file:
      - ./../.env
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: ${SWAGGER_UI_CONTAINER_NAME}
    volumes:
      - ./../src/openapi/openapi.yaml:/openapi.yaml
    ports:
      - ${SWAGGER_UI_PORT}:8080
    environment:
      SWAGGER_JSON: /openapi.yaml
  adminer:
    image: adminer
    container_name: ${ADMINER_CONTAINER_NAME}
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - database